### PR TITLE
LSPS0: Signal supported LSPS-version

### PR DESCRIPTION
**Pull request by ErikDeSmedt**
This PR unifies how for LSP-servers can signal what protocols and versions they support

### CODE REVIEW

**Comment by ErikDeSmedt** [comment]
This is an alternative proposal to PR https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/56.

**Comment by ZmnSCPxj-jr** [comment]
>The server just shows what versions it supports and the client can immediately start using the version it also supports rather then first having to tell the server I'm going to use version X.

This requires strictly more RPC turnarounds:

* client -> server "What versions do you support?"
* sever -> client "These are: <list>"
* client->server "Let us use this version: <n>"

Vs.

* client -> server "I support these versions: <list>"
* server -> client "Let us use this version: <n>"

**Comment by ErikDeSmedt** [comment]
> This requires strictly more RPC turnarounds:

I don't think that's a fair representation.

This proposal usually requires one round-trip
1. Client -> Server: What versions do you support?
2. Server -> Client: I support these versions
3. Client -> Server: This is usage. (E.g: `lsps1.v1.get_info`)

There is a single round-trip in `lsps0.list_protocols` here.

To my understanding any proposal requires at-least one round-trip. Either `lsps0.list_protocols` or `lsps0.select_versions` must be called.

**Comment by ZmnSCPxj-jr** [comment]
@ErikDeSmedt Not for LSPS4.  In LSPS4 in theory you could just call `get_scid` once, since the permanent SCID is permanent, and just cache it across multiple connections.  So for example the client negotiates version once, then calls `get_scid`, stores the SCID, then goes offline, then when it comes online again it can issue more invoices without having to call `get_scid` again.  However, the LSP cannot be sure about what version the client supports (the client can downgrade if e.g. there is a bug, so the LSP cannot safely cache the version) until the client actually makes *some* call.  In LSPS4, all payments to the permanent SCID are first informed to the client as notifications.  What version should the LSP use?  Again, it cannot safely use the version that the client mentioned in the previous connection, as the client might have gone offline because it was buggy and the human operator downgraded it to an older version.

This is the reason why the version negotiation in LSPS4 is done the way it is --- client says what versions it supports, LSP selects.  This allows the client to never call the LSP unless it actually gets a payment.

**Pull request closed without merging**
