### PR TITLE
Remove duplicate field `expires_at` in example

### PR DESCRIPTION
**Pull request by bufo24**

### CODE REVIEW

**Comment by ErikDeSmedt** [comment]
The field appears twice intentionally.

There is an `expires_at` for `bolt11` and another for `onchain` payments.

**Comment by bufo24** [comment]
But currently there are 3, 2 in the `onchain` object and 1 in the `bolt11` object.

A json object cannot have duplicate keys.

**Comment by ErikDeSmedt** [comment]
Oops, you're right

**Review by ErikDeSmedt — APPROVED** [review]

**Review by SeverinAlexB — APPROVED** [review]
Insta merge

**Pull request merged**
